### ISSUE TITLE
Build installer

### ISSUE THREAD

**Issue by austinginder** [CaptainCore/captaincore#3]
There is currently no way to install CaptainCore. Need to make an `install.sh` which could detect various environments and properly install CaptainCore with prerequisites. Once built, installing CaptainCore should be as simply as this:

```
curl -s https://captaincore.io/install.sh | sudo bash
```

**Comment by samjaninf** [comment]
I think this is probably necessary. I found this project a while a go, while trying to test it out  Iran into this issue:

```
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
panic: failed to connect database/root/.captaincore/data/sql.db

goroutine 1 [running]:
github.com/CaptainCore/captaincore/server.HandleRequests(0x0)
        /home/austin/.captaincore/server/server.go:434 +0xbf0
github.com/CaptainCore/captaincore/cmd.glob..func62(0xd3d0e0, 0xd7a920, 0x0, 0x0)
        /home/austin/.captaincore/cmd/server.go:12 +0x2c
github.com/spf13/cobra.(*Command).execute(0xd3d0e0, 0xd7a920, 0x0, 0x0, 0xd3d0e0, 0xd7a920)
        /home/austin/.captaincore/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xd3c460, 0x41ab01, 0x0, 0x0)
        /home/austin/.captaincore/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/austin/.captaincore/vendor/github.com/spf13/cobra/command.go:897
github.com/CaptainCore/captaincore/cmd.Execute()
        /home/austin/.captaincore/cmd/root.go:35 +0x2d
main.main()
        /home/austin/.captaincore/captaincore.go:8 +0x25
```

Before that I had to find and copy the config.json I found in the repo or else would run into this:
`$> captaincore server
open /root/.captaincore/data/config.json: no such file or directory
{[] []   }
`
Each of these I assume an install script would take care of. 😛

This project looks quite promising and the progress looks quite good and I'd love to give it a try when you get to that point. Thanks for sharing with us.

🎉

**Comment by woakes070048** [comment]
@austinginder hey wanted to check to see if you have looked at doing this or if you could provide some insight on how to manually install this. Thanks

**Comment by chriswathen** [comment]
@austinginder I'm also interested in this, I don't have an issue installing this manually. Just need some direction on it.

**Comment by CodeMeZone** [comment]
Any ETA with the installer?

**Comment by CodeMeZone** [comment]
@austinginder :)

**Comment by austinginder** [comment]
v1.0 of CaptainCore is out! New website and installer are ready: https://captaincore.io
